---
- hosts: worker
  tasks:

    - name: Instalasi Nginx, Git, Zip, dan Unzip
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      with_items:
        - nginx
        - git
        - python-software-properties
        - software-properties-common
        - zip
        - unzip
      notify: 
        - Restart nginx

    # Install PHP 7.2
    - name: Menambah Repositori PHP 7
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php' 
        update_cache: true

    - name: Install Package PHP 7.2
      become: yes
      apt: 
        name: "{{ item }}"
        state: latest
      with_items:
        - php7.2
        - php-pear
        - php7.2-curl
        - php7.2-dev
        - php7.2-gd
        - php7.2-mbstring
        - php7.2-zip
        - php7.2-mysql
        - php7.2-xml
        - php7.2-intl
        - php7.2-json
        - php7.2-cli
        - php7.2-common
        - php7.2-fpm
      notify: 
        - Restart PHP-fpm
    
    # Git Clone
    - name: Membuat direktori
      become: true
      file:
          path: "/var/www/laravel"
          state: directory
          owner: "{{ ansible_ssh_user }}"
          group: "{{ ansible_ssh_user }}"
          recurse: yes

    - name: Git Clone
      git:
        dest: "/var/www/laravel"
        repo: https://github.com/udinIMM/Hackathon.git
        force: yes

    # Install Composer
    - name: Download Composer
      script: script/composer.sh

    - name: Setting Composer menjadi Global
      become: true
      command: mv composer.phar /usr/local/bin/composer

    - name: Set Composer Permission
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    - name: Install Laravel Dependencies
      composer:
        working_dir: "/var/www/laravel"
        no_dev: no
    
    # Konfigurasi Environment
    - name: Konfigurasi .env
      command: cp "/var/www/laravel/.env.example" "/var/www/laravel/.env"
    
    - name: php artisan key generate
      command: php "/var/www/laravel/artisan" key:generate

    - name: php artisan clear cache
      command: php "/var/www/laravel/artisan" cache:clear
    
    - name: set APP_DEBUG=false
      lineinfile: 
        dest: "/var/www/laravel/.env"
        regexp: '^APP_DEBUG='
        line: APP_DEBUG=false

    - name: set APP_ENV=production
      lineinfile: 
        dest: "/var/www/laravel/.env"
        regexp: '^APP_ENV='
        line: APP_ENV=production

    - name: Mengganti Permission bootstrap/cache directory
      file:
        path: "/var/www/laravel/bootstrap/cache"
        state: directory
        mode: "a+x"

    - name: Mengganti Permission vendor directory
      command: chmod -R 777 "/var/www/laravel/vendor"

    - name: Mengganti Permission storage directory
      command: chmod -R 777 "/var/www/laravel/storage"
    
    # Konfigurasi Nginx
    - name: Konfigurasi Nginx
      become: true
      template:
        src: nginx/nginx.conf
        dest: /etc/nginx/sites-enabled/default
      notify:
        - Restart nginx
        - Restart PHP-fpm

  handlers:
    - name: Restart nginx
      become: true
      service: 
        name: nginx
        state: restarted

    - name: Restart PHP-fpm
      become: true
      service: 
        name: php7.2-fpm
        state: restarted
